M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu22.04.1} date 2024-06-19T00:01:22-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-19T00:01:22-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0709
%
G90
G05
T1
X4.0Y-2.9
X4.0Y-4.5
X4.6Y-2.9
X4.6Y-4.5
M30
